<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'An error occurred while installing Rights.' => 'Ocorreu um erro durante da instalação do Rights.',
  'Application authorization manager must extend the RDbAuthManager class.' => 'O gerenciador de autorizações da aplicação deve extender a classe RDbAuthManager.',
  'Application web user must extend the RWebUser class.' => 'O usuário web da aplicação deve extender a classe RWebUser.',
  'Congratulations!' => 'Parabéns!',
  'Error' => 'Erro',
  'Install Rights' => 'Intalar Rights',
  'No' => 'Não',
  'Notice: All your existing data will be lost.' => 'Aviso: Todos os seus dados serão perdidos.',
  'Please confirm if you wish to reinstall.' => 'Favor confirmar se você deseja reinstalar.',
  'Please try again or consult the documentation.' => 'Favor tentar novamente ou consulte a documentação.',
  'Rights has been installed succesfully.' => 'Rights foi instalado com sucesso.',
  'Rights is already installed!' => 'Rights já está instalado!',
  'Yes' => 'Sim',
  'You can start by generating your authorization items' => 'Você pode iniciar gerando seus itens de autorização',
  'You must be logged in to install Rights.' => 'Você deve estar logado para instalar o Rights.',
  'here' => 'aqui',
);
