<?php

class m131229_070705_carga_de_dados_de_curso_e_disciplina extends CDbMigration
{
	public function up()
	{
                $this->insert('tbl_curso', array('cod_curso'=>1, 'nome_curso'=>'Análise e Desenvolvimento de Sistemas'  , 'sigla_curso'=>'ADS'  , 'descricao_curso'=>'O Tecnólogo em Análise e Desenvolvimento de Sistemas analisa, projeta, documenta, especifica, testa, implanta e mantém sistemas computacionais de informação. Esse profissional trabalha, também, com ferramentas computacionais, equipamentos de informática e metodologia de projetos na produção de sistemas. Raciocínio lógico, emprego de linguagens de programação e de metodologias de construção de projetos, preocupação com a qualidade, usabilidade, robustez, integridade e segurança de programas computacionais são fundamentais à atuação desse profissional.'                                                                                                                                                                                                                                                                                                                                                                                                                     , 'duracao_curso'=>6));
                $this->insert('tbl_curso', array('cod_curso'=>2, 'nome_curso'=>'Sistemas para Internet'                 , 'sigla_curso'=>'SI'   , 'descricao_curso'=>'O Tecnólogo em Sistemas para Internet ocupa-se do desenvolvimento de programas, de interfaces e aplicativos, do comércio e do marketing eletrônicos, além de sítios e portais para Internet e intranet. Esse profissional gerencia projetos de sistemas, inclusive com acesso a banco de dados, desenvolve projetos de aplicações para a rede mundial de computadores e integra mídias nos sítios da Internet. Atua com tecnologias emergentes como computação móvel, redes sem fio e sistemas distribuídos. Cuidar da implantação, atualização, manutenção e segurança dos sistemas que utilizam a Internet como plataforma também são suas atribuições.'                                                                                                                                                                                                                                                                                                                                        , 'duracao_curso'=>6));
                $this->insert('tbl_curso', array('cod_curso'=>3, 'nome_curso'=>'Logística'                              , 'sigla_curso'=>'LG'   , 'descricao_curso'=>'O Tecnólogo em Logística é o profissional especializado em armazenagem, distribuição e transporte. Atuando na área logística de uma organização, planeja e coordena a movimentação física e de informações sobre as operações multimodais e intermodais de transporte, incluindo o gerenciamento de pessoas para proporcionar fluxo otimizado ao longo da cadeia de suprimentos. Ele projeta e gerencia redes de distribuição e unidades logísticas, estabelecendo processos de compras, identificando fornecedores, negociando e estabelecendo padrões de recebimento, armazenamento, movimentação e embalagem de materiais. Ocupa-se ainda do inventário e gerenciamento estratégico de estoques, sistemas de abastecimento, programação, monitoramento do fluxo de pedidos, cálculo de custos de fretes e transbordos, sistemas de tráfego e gerenciamento de transportes urbano de carga e passageiros, que envolvam os modais rodoviário, ferroviário, aeroviário, dutoviário e aquaviário.' , 'duracao_curso'=>6));
                $this->insert('tbl_curso', array('cod_curso'=>4, 'nome_curso'=>'Gestão Portuária'                       , 'sigla_curso'=>'GP'   , 'descricao_curso'=>'O Tecnólogo em Gestão Portuária é o profissional especializado em armazenagem e transporte em portos, com visão de intermodalidade. Em uma operadora ou concessionária, planeja e coordena a movimentação física e o fluxo de informações sobre as operações portuárias e suas necessidades intermodais de transporte, incluindo o gerenciamento de pessoas para proporcionar fluxo otimizado do ciclo origem-destino. Os sistemas logísticos portuários são projetados e gerenciados por este profissional com a utilização otimizada de equipamentos e as necessidades intermodais. Ocupa-se ainda do inventário e gerenciamento estratégico de armazenagem, cálculo de fretes, planejamento de transbordos, sistemas de tráfego de navios, gerenciamento de rebocadores, taxa de ocupação de berços, gerenciando todo o transporte aquaviário de carga e passageiros.'                                                                                                                         , 'duracao_curso'=>6));
                $this->insert('tbl_curso', array('cod_curso'=>5, 'nome_curso'=>'Gestão Empresarial'                     , 'sigla_curso'=>'GE'   , 'descricao_curso'=>''                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 , 'duracao_curso'=>6));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>701,'nome_disciplina'=>'CÁLCULO I','sigla_disciplina'=>'CALC -I','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>702,'nome_disciplina'=>'PORTUGUÊS INSTRUMENTAL I','sigla_disciplina'=>'PORT -I','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>703,'nome_disciplina'=>'INGLÊS INSTRUMENTAL I','sigla_disciplina'=>'ING -I','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>704,'nome_disciplina'=>'ADMINISTRAÇÃO','sigla_disciplina'=>'ADM','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>705,'nome_disciplina'=>'ARQUITETURA E ORGANIZAÇÃO DE COMPUTADORES','sigla_disciplina'=>'ARQOC','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>706,'nome_disciplina'=>'PROGRAMAÇÃO EM MICROINFORMÁTICA','sigla_disciplina'=>'PROGM','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>707,'nome_disciplina'=>'ALGORITMO E LÓGICA DE PROGRAMAÇÃO','sigla_disciplina'=>'ALGLOG','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>708,'nome_disciplina'=>'MONTAGEM E CONFIGURAÇÃO DE HARDWARE','sigla_disciplina'=>'MCD','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>709,'nome_disciplina'=>'CÁLCULO II','sigla_disciplina'=>'CALC-II','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>710,'nome_disciplina'=>'PORTUGUÊS INSTRUMENTAL II','sigla_disciplina'=>'PORT-II','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>711,'nome_disciplina'=>'INGLÊS INSTRUMENTAL II','sigla_disciplina'=>'ING-II','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>712,'nome_disciplina'=>'FUNDAMENTOS DE REDE','sigla_disciplina'=>'FUNRE','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>713,'nome_disciplina'=>'LINGUAGEM DE PROGRAMAÇÃO','sigla_disciplina'=>'LP','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>714,'nome_disciplina'=>'METODOLOGIA DA PESQ. APLICADA E TECNOLÓGICA','sigla_disciplina'=>'MPAT','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>715,'nome_disciplina'=>'CONTABILIDADE','sigla_disciplina'=>'CONTA','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>716,'nome_disciplina'=>'SISTEMAS DE INFORMAÇÃO','sigla_disciplina'=>'SI','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>717,'nome_disciplina'=>'MATEMÁTICA DISCRETA','sigla_disciplina'=>'MATD','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>718,'nome_disciplina'=>'PROGRAMAÇÃO ORIENTADA A OBJETOS','sigla_disciplina'=>'PROGO','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>719,'nome_disciplina'=>'ESTATÍSTICA APLICADA','sigla_disciplina'=>'ESTA','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>720,'nome_disciplina'=>'SISTEMAS OPERACIONAIS I','sigla_disciplina'=>'SO I','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>721,'nome_disciplina'=>'AMBIENTE OPERACIONAL','sigla_disciplina'=>'AO I','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>722,'nome_disciplina'=>'ENGENHARIA DE SOFTWARE I','sigla_disciplina'=>'ES I','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>723,'nome_disciplina'=>'PROGRAMAÇÃO LINEAR E APLICAÇÕES','sigla_disciplina'=>'PROGLA','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>724,'nome_disciplina'=>'ELETIVA I','sigla_disciplina'=>'ELE - I','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>725,'nome_disciplina'=>'SISTEMAS OPERACIONAIS II ','sigla_disciplina'=>' SO II','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>726,'nome_disciplina'=>'ENGENHARIA DE SOFTAWARE II','sigla_disciplina'=>'ES  II','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>727,'nome_disciplina'=>'BANCO DE DADOS','sigla_disciplina'=>'BD','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>728,'nome_disciplina'=>'ESTRUTURA DE DADOS','sigla_disciplina'=>'ESTD','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>729,'nome_disciplina'=>'ÉTICA E RESPONSABILIDADE PROFISSIONAL','sigla_disciplina'=>'ERP','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>730,'nome_disciplina'=>'RELAÇÕES HUMANAS','sigla_disciplina'=>'RH','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>731,'nome_disciplina'=>'ELETIVA II','sigla_disciplina'=>'ELE II','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>732,'nome_disciplina'=>'SEGURANÇA DA INFORMAÇÃO','sigla_disciplina'=>'SEGI','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>733,'nome_disciplina'=>'GESTÃO DE TECNOLOGIA DA INFORMAÇÃO','sigla_disciplina'=>'GTI','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>734,'nome_disciplina'=>'LABORATÓRIO DE BANCO DE DADOS','sigla_disciplina'=>'LBD','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>735,'nome_disciplina'=>'LABORATÓRIO DE ENGENHARIA DE SOFTWARE','sigla_disciplina'=>'LES','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>736,'nome_disciplina'=>'INTERAÇÃO HUMANO COMPUTADOR','sigla_disciplina'=>'IHC','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>737,'nome_disciplina'=>'HUMANIDADES PARA SISTEMAS DE INFORMAÇÃO','sigla_disciplina'=>'HIS','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>738,'nome_disciplina'=>'ELETIVA III','sigla_disciplina'=>'ELE III','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>739,'nome_disciplina'=>'AUDITORIA DE SISTEMAS','sigla_disciplina'=>'AS','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>740,'nome_disciplina'=>'SISTEMAS DISTRIBUÍDOS','sigla_disciplina'=>'SISD','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>741,'nome_disciplina'=>'TÓPICOS ESPECIAIS EM INFORMÁTICA','sigla_disciplina'=>'TEI','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>742,'nome_disciplina'=>'ECONOMIA E FINANÇAS','sigla_disciplina'=>'ECOFIN','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>743,'nome_disciplina'=>'GESTÃO DE PROJETOS','sigla_disciplina'=>'GESPRO','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>744,'nome_disciplina'=>'EMPREENDEDORISMO','sigla_disciplina'=>'EMPE','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>745,'nome_disciplina'=>'TRABALHO DE CONCLUSÃO DE CURSO','sigla_disciplina'=>'TCC','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>746,'nome_disciplina'=>'ESTÁGIO SUPERVISIONADO','sigla_disciplina'=>'ESTUSP','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>201,'nome_disciplina'=>'PROGRAMAÇÃO EM MICRO INFORMÁTICA','sigla_disciplina'=>'ILM-001','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>202,'nome_disciplina'=>'ALGORITMOS E LÓGICA DE PROGRAMAÇÃO','sigla_disciplina'=>'IAL-002','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>203,'nome_disciplina'=>'LABORATÓRIO DE HARDWARE','sigla_disciplina'=>'IHW-100','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>204,'nome_disciplina'=>'ARQUITETURA E ORGANIZAÇÃO DE COMPUTADORES','sigla_disciplina'=>'IAC-001','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>205,'nome_disciplina'=>'ADMINISTRAÇÃO GERAL','sigla_disciplina'=>'AAG-001','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>206,'nome_disciplina'=>'MATEMÁTICA DISCRETA','sigla_disciplina'=>'MMD-001','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>207,'nome_disciplina'=>'INGLÊS I','sigla_disciplina'=>'LIN-100','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>208,'nome_disciplina'=>'ENGENHARIA DE SOFTWARE I','sigla_disciplina'=>'IES-100','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>209,'nome_disciplina'=>'LINGUAGEM DE PROGRAMAÇÃO','sigla_disciplina'=>'ILP-010','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>210,'nome_disciplina'=>'SISTEMAS DE INFORMAÇÃO','sigla_disciplina'=>'ISI-002','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>211,'nome_disciplina'=>'CONTABILIDADE','sigla_disciplina'=>'CCG-001','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>212,'nome_disciplina'=>'CÁLCULO','sigla_disciplina'=>'MCA-002','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>213,'nome_disciplina'=>'COMUNICAÇÃO E EXPRESSÃO','sigla_disciplina'=>'LPO-001','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>214,'nome_disciplina'=>'INGLÊS II','sigla_disciplina'=>'LIN-200','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>215,'nome_disciplina'=>'ENGENHARIA DE SOFTWARE II','sigla_disciplina'=>'IES-200','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>216,'nome_disciplina'=>'INTERAÇÃO HUMANO COMPUTADOR','sigla_disciplina'=>'IHC-001','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>217,'nome_disciplina'=>'ESTRUTURA DE DADOS','sigla_disciplina'=>'IED-001','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>218,'nome_disciplina'=>'SISTEMAS OPERACIONAIS I','sigla_disciplina'=>'ISO-100','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>219,'nome_disciplina'=>'ECONOMIA E FINANÇAS','sigla_disciplina'=>'CEF-100','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>220,'nome_disciplina'=>'ESTATÍSTICA APLICADA','sigla_disciplina'=>'MET-100','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>221,'nome_disciplina'=>'SOCIEDADE E TECNOLOGIA','sigla_disciplina'=>'HST-002','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>222,'nome_disciplina'=>'INGLÊS III','sigla_disciplina'=>'LIN-300','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>223,'nome_disciplina'=>'ENGENHARIA DE SOFTWARE III','sigla_disciplina'=>'IES-300','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>224,'nome_disciplina'=>'PROGRAMAÇÃO ORIENTADA A OBJETOS','sigla_disciplina'=>'ILP-007','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>225,'nome_disciplina'=>'BANCO DE DADOS','sigla_disciplina'=>'IBD-002','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>226,'nome_disciplina'=>'SISTEMAS OPERACIONAIS II','sigla_disciplina'=>'ISO-200','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>227,'nome_disciplina'=>'ELETIVA I','sigla_disciplina'=>'ELETIVA I','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>228,'nome_disciplina'=>'METODOLOGIA DA PESQUISA CIENTIFICO-TECNOLOGICA','sigla_disciplina'=>'TTG-001','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>229,'nome_disciplina'=>'INGLÊS IV','sigla_disciplina'=>'LIN-400','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>230,'nome_disciplina'=>'LABORATÓRIO DE ENGENHARIA DE SOFTWARE','sigla_disciplina'=>'IES-301','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>231,'nome_disciplina'=>'SEGURANÇA DA INFORMAÇÃO','sigla_disciplina'=>'ISG-003','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>232,'nome_disciplina'=>'REDES DE COMPUTADORES','sigla_disciplina'=>'IRC-008','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>233,'nome_disciplina'=>'LABORATÓRIO DE BANCO DE DADOS','sigla_disciplina'=>'IBD-100','descricao_disciplina'=>''));
                //$this->insert('tbl_disciplina', array('cod_disciplina'=>233,'nome_disciplina'=>'SISTEMAS DISTRIBUIDOS','sigla_disciplina'=>'ISD-001','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>234,'nome_disciplina'=>'ELETIVA II','sigla_disciplina'=>'ELETIVA II','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>235,'nome_disciplina'=>'PROGRAMAÇÃO LINEAR E APLICAÇÕES','sigla_disciplina'=>'MPL-001','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>236,'nome_disciplina'=>'INGLÊS IV','sigla_disciplina'=>'LIN-500','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>237,'nome_disciplina'=>'GESTÃO DE PROJETOS','sigla_disciplina'=>'AGO-005','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>238,'nome_disciplina'=>'GESTÃO E GOVERNANÇA DE TECNOLOGIA DA INFORMAÇÃO','sigla_disciplina'=>'ITI-003','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>239,'nome_disciplina'=>'TÓPICOS ESPECIAIS EM INFORMÁTICA','sigla_disciplina'=>'ITE–002','descricao_disciplina'=>''));
                //$this->insert('tbl_disciplina', array('cod_disciplina'=>239,'nome_disciplina'=>'LABORATÓRIO DE REDES','sigla_disciplina'=>'IRC-100','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>240,'nome_disciplina'=>'INTELIGÊNCIA ARTIFICIAL','sigla_disciplina'=>'IIA–002','descricao_disciplina'=>''));
                //$this->insert('tbl_disciplina', array('cod_disciplina'=>240,'nome_disciplina'=>'AUDITORIA DE SISTEMAS','sigla_disciplina'=>'ISA–002','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>241,'nome_disciplina'=>'GESTÃO DE EQUIPES','sigla_disciplina'=>'AGR-101','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>242,'nome_disciplina'=>'EMPREENDEDORISMO','sigla_disciplina'=>'CEE-002','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>243,'nome_disciplina'=>'ÉTICA E RESPONSABILIDADE PROFISSIONAL','sigla_disciplina'=>'HSE-001','descricao_disciplina'=>''));
                $this->insert('tbl_disciplina', array('cod_disciplina'=>244,'nome_disciplina'=>'INGLÊS VI','sigla_disciplina'=>'LIN-600','descricao_disciplina'=>''));
	}

	public function down()
	{
		$this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>1));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>2));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>3));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>4));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>5));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>701));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>702));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>703));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>704));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>705));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>706));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>707));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>708));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>709));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>710));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>711));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>712));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>713));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>714));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>715));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>716));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>717));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>718));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>719));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>720));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>721));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>722));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>723));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>724));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>725));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>726));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>727));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>728));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>729));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>730));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>731));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>732));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>733));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>734));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>735));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>736));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>737));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>738));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>739));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>740));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>741));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>742));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>743));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>744));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>745));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>746));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>201));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>202));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>203));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>204));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>205));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>206));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>207));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>208));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>209));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>210));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>211));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>212));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>213));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>214));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>215));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>216));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>217));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>218));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>219));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>220));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>221));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>222));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>223));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>224));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>225));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>226));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>227));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>228));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>229));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>230));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>231));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>232));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>233));
                //$this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>233));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>234));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>235));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>236));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>237));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>238));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>239));
                //$this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>239));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>240));
                //$this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>240));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>241));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>242));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>243));
                $this->delete('tbl_curso','cod_curso=:cod_curso',array(':cod_curso'=>244));
	}
}