<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
        'Home'=>'Página Inicial',
        'About'=>'Sobre',
        'Contact'=>'Contato',
        'Error'=>'Erro',
        'Users'=>'Users',
        'Rights'=>'Rights',
        'Login'=>'Login',
        'Logout'=>'Logout',
        'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.'=>'Se você possui dúvidas comerciais ou outras questões gentileza preencher o formulário à seguir para entrar em contato. Obrigado.',
        'Fields with <span class="required">*</span> are required.' => 'Os campos com <span class="required"> * </span> são obrigatórios.',
        'Please enter the letters as they are shown in the image above.' => 'Por favor, digite as letras como mostrada na imagem.',
        'Letters are not case-sensitive.' => 'As letras não diferenciam entre maiúsculas e minúsculas.',
        'Operations'=>'Operações',
        'Name'=>'Nome',
        'E-mail'=>'E-mail',
        'Subject'=>'Assunto',
        'Body'=>'Mensagem',
        'Verification Code'=>'Código de Verificação',
);
