<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
        'Home'=>'Página Inicial',
        'About'=>'Sobre',
        'Contact'=>'Contato',
        'Error'=>'Erro',
        'Users'=>'Users',
        'Rights'=>'Rights',
        'Login'=>'Conectar',
        'Logout'=>'Desconectar',
        'Logged In as'=>'Conectado como',
        'Logged Off'=>'Desconectado',
        'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.'=>'Se você possui dúvidas comerciais ou outras questões gentileza preencher o formulário à seguir para entrar em contato. Obrigado.',
        'Thank you for contacting us. We will respond to you as soon as possible.'=>'Obrigado pelo contato. Responderemos o mais breve possível.',
        'Fields with <span class="required">*</span> are required.' => 'Os campos com <span class="required"> * </span> são obrigatórios.',
        'Please enter the letters as they are shown in the image above.' => 'Por favor, digite as letras como mostrada na imagem.',
        'Letters are not case-sensitive.' => 'As letras não diferenciam entre maiúsculas e minúsculas.',
        'Operations'=>'Operações',
        'Name'=>'Nome',
        'E-mail'=>'E-mail',
        'Subject'=>'Assunto',
        'Body'=>'Mensagem',
        'Verification Code'=>'Código de Verificação',
        'Create'=>'Criar',
        'List'=>'Listar',
        'Update'=>'Atualizar',
        'Delete'=>'Deletar',
        'Manage'=>'Gerenciar',
        'Save'=>'Salvar',
        'You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.'=>'Você pode optar por utilizar um operador de comparação (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> ou <b>=</b>) no incício de cada um dos seus valores de busca para especificar como a comparação deve ser feita.',
        'Advanced Search'=>'Busca Avançada',
        'Fields with <span class="required">*</span> are required.'=>'Campos com <span class="required">*</span> são obrigatórios.',
        'Are you sure you want to delete this item?'=>'Você tem certeza que deseja deletar este item?',
        'Subjects'=>'Disciplinas',
        'View Subject'=>'Visualizar Disciplina',
        'Create Subject'=>'Criar Disciplina',
        'List Subjects'=>'Listar Disciplinas',
        'Update Subject'=>'Atualizar Disciplina',
        'Delete Subject'=>'Deletar Disciplina',
        'Manage Subjects'=>'Gerenciar Disciplinas',
        'Courses'=>'Cursos',
        'View Course'=>'Visualizar Curso',
        'Create Course'=>'Criar Curso',
        'List Courses'=>'Listar Cursos',
        'Update Course'=>'Atualizar Curso',
        'Delete Course'=>'Deletar Curso',
        'Manage Courses'=>'Gerenciar Cursos',
        'Students'=>'Alunos',
        'View Student'=>'Visualizar Aluno',
        'List Students'=>'Listar Alunos',
	'Create Student'=>'Criar Aluno',
	'Update Student'=>'Atualizar Aluno',
	'Delete Student'=>'Deletar Aluno',
	'Manage Students'=>'Gerenciar Alunos',
        'Student Register'=>'Cadastro de Aluno',
        'Personal Data'=>'Dados Pessoais',
        'Student Data'=>'Dados do Aluno',
        'Professors'=>'Professores',
        'View Professor'=>'Visualizar Professor',
        'List Professors'=>'Listar Professores',
	'Create Professor'=>'Criar Professor',
	'Update Professor'=>'Atualizar Professor',
	'Delete Professor'=>'Deletar Professor',
	'Manage Professors'=>'Gerenciar Professores',
        'Professor Register'=>'Cadastro de Professor',
        'Professor Data'=>'Dados do Professor',
);